/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../public/Airplane.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Airplane=(props)=>{
  const { nodes, materials } = useGLTF('/Airplane.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PUSHILIN_Plane_Circle000.geometry} material={materials.plane} />
    </group>
  )
}

useGLTF.preload('/Airplane.glb')

export default Airplane;
