/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../public/Clouds.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Clouds =(props)=> {
  const { nodes, materials } = useGLTF('/Clouds.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node.geometry} material={materials.mat21} />
    </group>
  )
}

useGLTF.preload('/Clouds.glb')

export default Clouds;
